version: "3.9"

services:
  echo-server:
    build: .
    ports:
      - "5173:5173"
    environment:
      - DB_HOST=109.123.234.160
      - DB_PORT=2080
      - DB_USER=root
      - DB_PASSWORD=lcbisa88  
      - DB_NAME=DataAnalyst
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    networks:
      - app_network  
    depends_on:
      - jaeger
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.56  # Versi terbaru Jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger Collector GRPC
      - "14269:14269"  # Jaeger Collector HTTP
      - "6831:6831/udp"
      - "6832:6832/udp"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:v2.52.0 
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network

  grafana:
    image: grafana/grafana:10.3.1 
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./config/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app_network

networks:
  app_network:
