global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'echo-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['echo-server:5173']

  - job_name: 'jaeger'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jaeger:14269']
